# Generated by Django 2.1.3 on 2018-11-13 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordblacklist',
            old_name='mots',
            new_name='words',
        ),
    ]
