# Generated by Django 2.1.3 on 2018-11-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20181113_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('identifiant', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
