# Generated by Django 2.1.3 on 2018-11-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='identifiant',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
